### ISSUE TITLE
(API) Make sure IDN is properly working for any TLD

### ISSUE THREAD

**Issue by frdmn** [frdmn/webwhois#19]

**Comment by frdmn** [comment]
Raised https://github.com/hjr265/node-whois/pull/29 to fix incorrect passing of the punycode option

**Comment by frdmn** [comment]
This can be closed as soon as theres a new NPM package :)

**Comment by hjr265** [comment]
Sorry for the delay.. I have been traveling last couple of days. I will do this within the next 24 hours as soon as I settle down a little.

**Comment by frdmn** [comment]
@hjr265 No problem, take your time! I can work with a hardcoded fix in my node_modules in the meantime. 👍
